services:
  - type: web
    name: webrtc-video-chat
    env: node
    plan: free
    rootDir: 17WebRTC
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
